spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/isk
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    mapping-resources:
      - persistence/isk-orm.xml
  liquibase:
    change-log: classpath:persistence/db/changelog/changelog-master.xml
  thymeleaf:
    check-template-location: true
  mail:
    host: ${SMTP_HOST:localhost}
    port: ${SMTP_PORT:2525}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

notifications:
  email:
    enabled: ${NOTIFICATIONS_EMAIL_ENABLED:false}
    from: ${NOTIFICATIONS_EMAIL_FROM:no-reply@isk.sk}

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  config:
    activate:
      on-profile: keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/ISK
          jwk-set-uri: http://localhost:8080/auth/realms/ISK/protocol/openid-connect/certs